import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../node_modules/bootstrap/scss/_reboot.scss";
import "../../node_modules/bootstrap/scss/_root.scss";
import "../bootstrap/all.scss";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-bs-theme="dark">
      <body>
        {children}
        <svg className="hide-svg-defs hide-visually">
          <filter id="saturate-opacity">
            <feComponentTransfer>
              <feFuncA type="linear" slope="99999" intercept="0"></feFuncA>
            </feComponentTransfer>
          </filter>
        </svg>
      </body>
    </html>
  );
}
